---
- name: copy mongodb.repo into yum.repos.d
  ansible.builtin.copy:
   src: mongodb.repo
   dest: /etc/yum.repos.d/mongo.repo
- name: Install mongodb package 
  ansible.builtin.yum:
   name: mongodb 
   state: installed
   update_cache: yes
- name: start and enable service
  ansible.builtin.yum:
   name: mongod
   state: started
   enabled: true 
- name: enable remote connections to mongodb
  ansible.builtin.replace:
   regexp: '127.0.0.1'
   replace: '0.0.0.0'
   path: /etc/mongod.conf
- name: restart mongod service:
  ansible.builtin.service:
   name: mongod
   state: restarted
...