# I need to refer nodejs tasks in common folder
# catalogue is one role
# common is also another role
# I need to import a task nodejs.yaml in catalogue

- name: Installing nodejs 
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs

- name: Setup application
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup

- name: Install dependencies
  ansible.builtin.command: npm install
  args:
   chdir: /app

- name: Configuing catalogue service
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd-setup

- name: Load schema into mongodb client
  ansible.builtin.import_role:
   name: common
   tasks_from: load-mongo-schema
