- name: copy {{component}} service
  ansible.builtin.copy:
   src: "{{component}}.service"
   dest: /etc/systemd/system/catalogue.service

- name: reload daemon
  ansible.builtin.systemd:
   daemon_reload: true

- name: start and enable service
  ansible.builtin.service:
   name: catalogue
   state: started
   enabled: true