- name: Install nodejs 
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs
  
- name: setup application
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup

- name: Install dependencies
  ansible.builtin.command: npm install
  args:
   chdir: /app

- name: copy {{component}} service
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd-setup